/**
 * Normalizes `public/data/hexbins.json` into a single shape the app can rely on,
 * regardless of which pipeline version produced it.
 *
 * The data file is a build artefact regenerated by `npm run data:fetch`, and a
 * checkout can easily be running a v1 file against v3 application code. Rather
 * than make the app fail — or worse, silently mis-score — this module upgrades
 * older files in memory and flags precisely what is degraded.
 */

import type {
  HexbinRecord,
  HexbinsFile,
  NormalizedHexbinsFile,
  RawHexbinRecord,
  TaxonFilter,
  TaxonRecord,
} from './types'
import { TAXON_FILTERS } from './taxonomy'

export const CURRENT_SCHEMA_VERSION = 3

/**
 * Stand-in for a filter a hexbin has no records under.
 *
 * Schema v3 omits empty filters rather than storing an empty record for each of
 * them — six mostly-zero records across ~6,300 hexbins is a large share of the
 * data file for no information. Reads go through `taxonDataFor`, which
 * substitutes this, so callers never branch on absence.
 *
 * Frozen because every such read shares this one instance. The realistic hazard
 * is `upgradeFromTopSpecies`, which assigns `speciesIds` onto records it walks:
 * freezing turns a stray write into a visible error rather than a value that
 * silently leaks into every empty filter of every hexbin.
 */
const EMPTY_TAXON_RECORD: TaxonRecord = Object.freeze({
  occurrenceCount: 0,
  uniqueSpeciesCount: 0,
  uniqueObserverCount: 0,
  uniqueDateCount: 0,
  temporalSpanYears: 0,
  firstDate: null,
  lastDate: null,
  topSpecies: [],
  speciesIds: [],
  countsBySource: {},
})

/** The taxon record for one filter, or an empty one when the filter has no records. */
export function taxonDataFor(hex: HexbinRecord, filter: TaxonFilter): TaxonRecord {
  return hex.taxa[filter] ?? EMPTY_TAXON_RECORD
}

/**
 * True when every hexbin carries the same habitat value, which is what
 * `npm run data:habitat-fallback` produces when the real Atlantic Forest
 * GeoJSON has not been downloaded.
 *
 * A constant cannot discriminate between hexbins: including it in the frontier
 * score adds a fixed offset to every result, inflating the numbers and
 * compressing the visible range while changing no ordering. Detecting it lets
 * the scorer drop the component and renormalise instead — and lets the UI say
 * so out loud rather than presenting a placeholder as a measurement.
 */
export function habitatDataIsPlaceholder(hexbins: HexbinsFile['hexbins']): boolean {
  if (hexbins.length < 2) return true
  const first = hexbins[0].habitatQuality
  return hexbins.every(h => h.habitatQuality === first)
}

/**
 * Folds a stored hexbin into the `taxa` map the app reads from.
 *
 * v3 files already carry one. v1 and v2 carried exactly two fixed fields, so
 * the upgrade is a rename — and the resulting map has only those two keys,
 * which is what makes `resolveAvailableFilters` hide the newer filters on an
 * old data file instead of offering filters that would come back empty.
 */
function toHexbinRecord(raw: RawHexbinRecord): HexbinRecord {
  if (raw.taxa) return raw as HexbinRecord

  const taxa: Partial<Record<TaxonFilter, TaxonRecord>> = {}
  if (raw.all)         taxa.all         = raw.all
  if (raw.vertebrates) taxa.vertebrates = raw.vertebrates
  return { ...raw, taxa }
}

/**
 * Filters that actually have records in this dataset, in display order.
 *
 * The selector is built from this rather than from `TAXON_FILTERS`, so a v2
 * data file offers only All Taxa and Vertebrates while a v3 file offers the
 * full set. Offering a filter with no records would rank nothing and read as a
 * broken tool rather than as an out-of-date data file.
 *
 * `all` is always included: it is the default selection, and a selector with no
 * options is worse than one showing an empty dataset.
 */
export function resolveAvailableFilters(hexbins: HexbinRecord[]): TaxonFilter[] {
  return TAXON_FILTERS.filter(filter =>
    filter === 'all' ||
    hexbins.some(hex => (hex.taxa[filter]?.occurrenceCount ?? 0) > 0),
  )
}

/**
 * Reconstructs a species index for a v1 file from the per-hexbin `topSpecies`
 * lists, which are the only species names such a file carries.
 *
 * This is lossy by construction: v1 stores at most 10 species per hexbin while
 * `uniqueSpeciesCount` routinely runs into the hundreds. Incompleteness scoring
 * still produces a usable signal from it, but against a systematically
 * understated expected-species pool — hence `speciesDataIsPartial`.
 */
function upgradeFromTopSpecies(hexbins: HexbinRecord[]): string[] {
  const index: string[] = []
  const idByName = new Map<string, number>()

  const assign = (record: TaxonRecord) => {
    const ids: number[] = []
    for (const { name } of record.topSpecies) {
      let id = idByName.get(name)
      if (id === undefined) {
        id = index.length
        index.push(name)
        idByName.set(name, id)
      }
      ids.push(id)
    }
    record.speciesIds = ids
  }

  for (const hex of hexbins) {
    for (const record of Object.values(hex.taxa)) assign(record)
  }

  return index
}

export function normalizeHexbinsFile(file: HexbinsFile): NormalizedHexbinsFile {
  const version = file.schemaVersion ?? 1
  const habitatIsPlaceholder = habitatDataIsPlaceholder(file.hexbins)
  const hexbins = file.hexbins.map(toHexbinRecord)
  const availableFilters = resolveAvailableFilters(hexbins)

  // The species index arrived with the file from v2 onward; only its absence
  // forces the lossy rebuild below, so v2 and v3 take the same path here.
  if (file.speciesIndex) {
    return {
      ...file,
      hexbins,
      schemaVersion: version,
      speciesIndex: file.speciesIndex,
      sources: file.sources ?? [],
      availableFilters,
      speciesDataIsPartial: false,
      habitatIsPlaceholder,
    }
  }

  // Mutates the freshly-parsed hexbin records in place to attach speciesIds.
  // Safe because this runs once on the just-fetched JSON, before anything else
  // holds a reference to it.
  const speciesIndex = upgradeFromTopSpecies(hexbins)

  return {
    ...file,
    hexbins,
    schemaVersion: version,
    speciesIndex,
    sources: file.sources ?? [],
    availableFilters,
    speciesDataIsPartial: true,
    habitatIsPlaceholder,
  }
}
