/**
 * Normalizes `public/data/hexbins.json` into a single shape the app can rely on,
 * regardless of which pipeline version produced it.
 *
 * The data file is a build artefact regenerated by `npm run data:fetch`, and a
 * checkout can easily be running a v1 file against v2 application code. Rather
 * than make the app fail — or worse, silently mis-score — this module upgrades
 * v1 files in memory and flags precisely what is degraded.
 */

import type {
  HexbinsFile,
  NormalizedHexbinsFile,
  TaxonRecord,
} from './types'

export const CURRENT_SCHEMA_VERSION = 2

/**
 * True when every hexbin carries the same habitat value, which is what
 * `npm run data:habitat-fallback` produces when the real Atlantic Forest
 * GeoJSON has not been downloaded.
 *
 * A constant cannot discriminate between hexbins: including it in the frontier
 * score adds a fixed offset to every result, inflating the numbers and
 * compressing the visible range while changing no ordering. Detecting it lets
 * the scorer drop the component and renormalise instead — and lets the UI say
 * so out loud rather than presenting a placeholder as a measurement.
 */
export function habitatDataIsPlaceholder(hexbins: HexbinsFile['hexbins']): boolean {
  if (hexbins.length < 2) return true
  const first = hexbins[0].habitatQuality
  return hexbins.every(h => h.habitatQuality === first)
}

/**
 * Reconstructs a species index for a v1 file from the per-hexbin `topSpecies`
 * lists, which are the only species names such a file carries.
 *
 * This is lossy by construction: v1 stores at most 10 species per hexbin while
 * `uniqueSpeciesCount` routinely runs into the hundreds. Incompleteness scoring
 * still produces a usable signal from it, but against a systematically
 * understated expected-species pool — hence `speciesDataIsPartial`.
 */
function upgradeFromTopSpecies(hexbins: HexbinsFile['hexbins']): string[] {
  const index: string[] = []
  const idByName = new Map<string, number>()

  const assign = (record: TaxonRecord) => {
    const ids: number[] = []
    for (const { name } of record.topSpecies) {
      let id = idByName.get(name)
      if (id === undefined) {
        id = index.length
        index.push(name)
        idByName.set(name, id)
      }
      ids.push(id)
    }
    record.speciesIds = ids
  }

  for (const hex of hexbins) {
    assign(hex.all)
    assign(hex.vertebrates)
  }

  return index
}

export function normalizeHexbinsFile(file: HexbinsFile): NormalizedHexbinsFile {
  const version = file.schemaVersion ?? 1
  const habitatIsPlaceholder = habitatDataIsPlaceholder(file.hexbins)

  if (version >= CURRENT_SCHEMA_VERSION && file.speciesIndex) {
    return {
      ...file,
      schemaVersion: version,
      speciesIndex: file.speciesIndex,
      sources: file.sources ?? [],
      speciesDataIsPartial: false,
      habitatIsPlaceholder,
    }
  }

  // Mutates the freshly-parsed hexbin records in place to attach speciesIds.
  // Safe because this runs once on the just-fetched JSON, before anything else
  // holds a reference to it.
  const speciesIndex = upgradeFromTopSpecies(file.hexbins)

  return {
    ...file,
    schemaVersion: version,
    speciesIndex,
    sources: file.sources ?? [],
    speciesDataIsPartial: true,
    habitatIsPlaceholder,
  }
}
