/**
 * Writes the seed migration for location obscuring: the threatened species
 * lists and the resolution-5 cell centroids a sensitive record snaps to.
 *
 * The lists come from SIBBR's species list service, which publishes the
 * annexes of Portaria MMA 148/2022 and the Santa Catarina lists as JSON. Which
 * lists, and the snapshot date the methodology panel shows, are set in
 * `src/lib/sensitive-taxa.ts`; this script only downloads what that file
 * names.
 *
 *   npm run data:sensitive-taxa -- supabase/migrations/<timestamp>_seed_sensitive_locations.sql
 *
 * A refresh goes into a new migration rather than over the old one, so the
 * database history says when the lists changed. The output truncates and
 * reloads both tables, so it is safe to apply on top of an earlier seed.
 */
import { writeFileSync } from 'fs'
import { resolve } from 'path'
import { cellToLatLng, cellToParent, polygonToCells } from 'h3-js'
import { SENSITIVE_LOCATIONS, taxonNameKey } from '../src/lib/sensitive-taxa'
import { fetchJson } from './sources/http'

const OUTPUT = resolve(process.argv[2] ?? 'supabase/migrations/20261001000002_seed_sensitive_locations.sql')
const SIBBR = 'https://specieslist.sibbr.gov.br/ws/speciesListItems'

/**
 * The bounding box `submissions` accepts (its latitude and longitude CHECKs),
 * widened by about one resolution-6 cell so a cell whose centre falls just
 * outside still has its parent seeded.
 */
const BBOX = { south: -29.6, north: -25.7, west: -54.1, east: -48.1 }

interface SibbrItem {
  name: string
  scientificName?: string
  kvpValues?: Array<{ key: string; value: string }>
}

interface Entry {
  name: string
  sources: Set<string>
  categories: Set<string>
}

async function fetchList(uid: string): Promise<SibbrItem[]> {
  // The largest list (national flora) is about 3,200 items; one page holds it.
  const items = await fetchJson<SibbrItem[]>(`${SIBBR}/${uid}?max=10000&includeKVP=true`, { timeoutMs: 120_000 })
  if (!Array.isArray(items) || items.length === 0) throw new Error(`SIBBR list ${uid} came back empty`)
  return items
}

function sql(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

function sqlArray(values: Iterable<string>): string {
  return `array[${[...values].sort().map(sql).join(', ')}]::text[]`
}

async function main() {
  const entries = new Map<string, Entry>()
  const skipped: string[] = []

  for (const list of SENSITIVE_LOCATIONS.lists) {
    const items = await fetchList(list.uid)
    let kept = 0
    for (const item of items) {
      const key = taxonNameKey(item.name)
      if (!key) { skipped.push(`${list.code}: ${item.name}`); continue }
      const status = item.kvpValues?.find(kv => kv.key === 'status')?.value
      const entry = entries.get(key) ?? { name: item.name, sources: new Set(), categories: new Set() }
      entry.sources.add(list.code)
      if (status) entry.categories.add(status)
      entries.set(key, entry)
      kept++
    }
    console.log(`${list.code}: ${items.length} items, ${kept} keyed`)
  }

  const bbox = [[
    [BBOX.south, BBOX.west], [BBOX.south, BBOX.east],
    [BBOX.north, BBOX.east], [BBOX.north, BBOX.west],
  ]]
  const parents = new Set(polygonToCells(bbox, 6).map(c => cellToParent(c, SENSITIVE_LOCATIONS.resolution)))

  const lines: string[] = [
    '-- Generated by scripts/build-sensitive-taxa.ts. Do not edit by hand.',
    `-- Snapshot ${SENSITIVE_LOCATIONS.snapshotDate}: ${entries.size} species keys from`,
    ...SENSITIVE_LOCATIONS.lists.map(l => `--   ${l.code}: ${l.label} (SIBBR ${l.uid})`),
    `-- and ${parents.size} resolution-${SENSITIVE_LOCATIONS.resolution} cell centroids over the SC bounding box.`,
    '',
    'truncate public.sensitive_taxa;',
    'truncate public.obscuring_cells;',
    '',
    'insert into public.sensitive_taxa (name_key, scientific_name, sources, categories) values',
    [...entries.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, e]) => `  (${sql(key)}, ${sql(e.name)}, ${sqlArray(e.sources)}, ${sqlArray(e.categories)})`)
      .join(',\n') + ';',
    '',
    'insert into public.obscuring_cells (cell, latitude, longitude) values',
    [...parents].sort().map(cell => {
      const [lat, lng] = cellToLatLng(cell)
      return `  (${sql(cell)}, ${lat.toFixed(6)}, ${lng.toFixed(6)})`
    }).join(',\n') + ';',
    '',
  ]

  writeFileSync(OUTPUT, lines.join('\n'))
  console.log(`${entries.size} species keys, ${parents.size} cells -> ${OUTPUT}`)
  if (skipped.length) console.log(`skipped ${skipped.length} names with no epithet:\n  ${skipped.join('\n  ')}`)
}

main().catch(err => { console.error(err); process.exit(1) })
