-- ============================================================================
-- BioFrontier SC: obscure the location of threatened taxa.
--
-- A community record is a point at the centre of the observer's resolution-6
-- hexbin (about 36 km²), and until now everyone could read it: anonymous
-- callers through `approved_submissions`, signed-in callers straight from
-- `submissions`. For a species on an official threatened list that hands its
-- whereabouts to anyone who wants to collect it. iNaturalist hides those
-- records behind a coarse box; this does the same.
--
-- Rule: a record is sensitive when its name, or any name a reviewer proposed
-- for it, matches a species on one of the lists in `sensitive_taxa`. Other
-- people then see it at the centre of its resolution-5 H3 parent (about
-- 252 km²) with no hexbin id. The observer still sees their own record
-- exactly. A name that matches nothing is shown exactly, which is the stated
-- limit: a synonym or a misspelling is not caught.
--
-- Why snap to a cell centre rather than move the point at random inside it:
-- a fresh random offset on each read averages back to the true point, and a
-- stored one adds a column to protect. A centre is the same on every read and
-- carries no more than "somewhere in this cell".
--
-- Enforcement is in the database, not the client:
--
--   * authenticated callers lose SELECT on the location columns of
--     `submissions` (hex_id, latitude, longitude). They keep the columns that
--     an UPDATE of their own row needs to find it.
--   * `community_submissions` replaces the direct table read for signed-in
--     reviewers, and `approved_submissions` is redefined. Both compute the
--     published location here, so nothing exact leaves the database for
--     anyone but the observer.
--
-- Lists and cell centroids are seeded by the following migration, which
-- `scripts/build-sensitive-taxa.ts` generates.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- The lists. One row per matching key, with every list it appears on.
-- ---------------------------------------------------------------------------
create table if not exists public.sensitive_taxa (
  name_key        text primary key,
  scientific_name text not null,
  sources         text[] not null,
  categories      text[] not null default '{}'
);

comment on table public.sensitive_taxa is
  'Species whose community records are published at a coarse location. Union of the lists named in src/lib/sensitive-taxa.ts, matched on genus + epithet. Seeded, never client-written.';

-- Centroid of every resolution-5 cell that is a parent of a resolution-6 cell
-- in the Santa Catarina bounding box `submissions` accepts. Postgres has no H3
-- extension here, so the centroids are computed once by h3-js and stored.
create table if not exists public.obscuring_cells (
  cell      text primary key check (cell ~ '^[0-9a-f]{15}$'),
  latitude  double precision not null,
  longitude double precision not null
);

comment on table public.obscuring_cells is
  'Centroids of the H3 resolution-5 cells a sensitive record is snapped to. Generated by h3-js, see scripts/build-sensitive-taxa.ts.';

-- Both are public reference data: the lists are published law and a cell
-- centre says nothing about any record. Readable, never client-writable.
alter table public.sensitive_taxa  enable row level security;
alter table public.obscuring_cells enable row level security;

drop policy if exists sensitive_taxa_read  on public.sensitive_taxa;
drop policy if exists obscuring_cells_read on public.obscuring_cells;
create policy sensitive_taxa_read  on public.sensitive_taxa  for select to anon, authenticated using (true);
create policy obscuring_cells_read on public.obscuring_cells for select to anon, authenticated using (true);

grant  select                             on public.sensitive_taxa, public.obscuring_cells to anon, authenticated;
revoke insert, update, delete, truncate     on public.sensitive_taxa, public.obscuring_cells from anon, authenticated;


-- ---------------------------------------------------------------------------
-- Matching key: genus + specific epithet, lower case, qualifiers and
-- subgenera dropped. Mirrors `taxonNameKey` in src/lib/sensitive-taxa.ts.
-- ---------------------------------------------------------------------------
create or replace function public.taxon_name_key(p_name text)
returns text language sql immutable as $$
  with tokens as (
    select array_agg(tok order by ord) as t
    from unnest(regexp_split_to_array(lower(btrim(coalesce(p_name, ''))), '\s+'))
         with ordinality as u(tok, ord)
    where tok <> ''
      and tok not in ('cf.', 'cf', 'aff.', 'aff', '?')
      and tok !~ '^\(.*\)$'
  )
  select case
    when coalesce(array_length(t, 1), 0) >= 2 and t[2] not in ('sp.', 'sp', 'spp.', 'spp')
      then t[1] || ' ' || t[2]
  end
  from tokens
$$;


-- ---------------------------------------------------------------------------
-- H3 parent at resolution 5, by bit arithmetic on the index.
--
-- An H3 cell index keeps its resolution in bits 52-55 and one 3-bit digit per
-- resolution below that, digit r at bits 3*(15-r) .. 3*(15-r)+2. The parent at
-- resolution 5 is the same index with the resolution set to 5 and digit 6 set
-- to 7, the "unused" marker. Returns null for anything that is not a
-- resolution-6 cell, so a malformed id fails closed (no location) rather than
-- open.
-- ---------------------------------------------------------------------------
create or replace function public.h3_parent_res5(p_cell text)
returns text language plpgsql immutable as $$
declare
  v bigint;
begin
  if p_cell is null or p_cell !~ '^[0-9a-f]{15}$' then
    return null;
  end if;
  v := ('x' || lpad(p_cell, 16, '0'))::bit(64)::bigint;
  if ((v >> 52) & 15) <> 6 then
    return null;
  end if;
  v := (v & ~(15::bigint << 52)) | (5::bigint << 52);
  v := v | (7::bigint << 27);
  return lpad(to_hex(v), 15, '0');
end $$;


-- ---------------------------------------------------------------------------
-- Is this record sensitive? Its own name, or any name a reviewer proposed.
-- A reviewer correcting a common species to a threatened one hides the point
-- from then on, which is the direction a disagreement should err in.
-- Security definer so it can read identifications for any caller; it returns
-- one boolean and nothing else.
-- ---------------------------------------------------------------------------
create or replace function public.submission_is_sensitive(p_submission_id uuid, p_scientific_name text)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.sensitive_taxa t
    where t.name_key = public.taxon_name_key(p_scientific_name)
  ) or exists (
    select 1
    from public.identifications i
    join public.sensitive_taxa t on t.name_key = public.taxon_name_key(i.proposed_name)
    where i.submission_id = p_submission_id
  )
$$;


-- ---------------------------------------------------------------------------
-- Column access on the base table.
--
-- Supabase grants table-wide SELECT to anon and authenticated. Replace it with
-- the columns that carry no location. `id`, `observer_id` and `status` are
-- what the update policy and an observer withdrawing their own record need.
-- Reads for display go through the views below.
-- ---------------------------------------------------------------------------
--
-- Grants are stated rather than inherited. The hosted project was created when
-- Supabase still granted every privilege on new tables by default; a local
-- stack from a current CLI grants none, and this migration should mean the
-- same thing in both.
revoke select on public.submissions from anon, authenticated;
grant select (id, observer_id, status, observed_on, scientific_name, class_name,
              gbif_species_key, notes, created_at, updated_at)
  on public.submissions to authenticated;
grant insert, update on public.submissions to authenticated;


-- ---------------------------------------------------------------------------
-- The location as the caller may see it: exact when the taxon is not listed
-- or the caller is the observer, otherwise the resolution-5 cell centre.
-- ---------------------------------------------------------------------------
-- Columns are spelled out rather than taken from `s.*`: a column added to
-- `submissions` later must not become readable through these views by
-- accident.
create or replace view public.community_submissions
with (security_invoker = false) as
select
  s.id,
  s.observer_id,
  s.status,
  s.observed_on,
  s.scientific_name,
  s.class_name,
  s.gbif_species_key,
  s.notes,
  s.created_at,
  sens.v as sensitive,
  (sens.v and s.observer_id is distinct from auth.uid()) as location_obscured,
  case when not sens.v or s.observer_id = auth.uid() then s.hex_id end as hex_id,
  case when sens.v and s.observer_id is distinct from auth.uid()
       then public.h3_parent_res5(s.hex_id) end as obscured_cell,
  case when not sens.v or s.observer_id = auth.uid() then s.latitude  else c.latitude  end as latitude,
  case when not sens.v or s.observer_id = auth.uid() then s.longitude else c.longitude end as longitude
from public.submissions s
-- Lateral rather than a CTE: PostgREST traces a view's columns back to their
-- table to offer embedding (`identifications(...)`), and it cannot see
-- through a CTE.
cross join lateral (select public.submission_is_sensitive(s.id, s.scientific_name) as v) sens
left join public.obscuring_cells c on c.cell = public.h3_parent_res5(s.hex_id)
-- The view runs as its owner and so bypasses the table's RLS. This line is
-- the RLS: signed-in callers only, exactly as `submissions_read_authed`.
where auth.uid() is not null;

comment on view public.community_submissions is
  'Every submission as a signed-in caller may see it: sensitive taxa are snapped to their resolution-5 cell centre and lose hex_id, except for the observer. Replaces direct SELECT on submissions.';

revoke all on public.community_submissions from anon, authenticated, public;
grant select on public.community_submissions to authenticated;


-- Public map layer. Same rule; for an anonymous caller auth.uid() is null, so
-- every sensitive record is obscured. Columns that already existed keep their
-- names and order, so `create or replace` applies; the new ones go last.
create or replace view public.approved_submissions
with (security_invoker = false) as
select
  s.id,
  case when not sens.v or s.observer_id = auth.uid() then s.hex_id end as hex_id,
  case when not sens.v or s.observer_id = auth.uid() then s.latitude  else c.latitude  end as latitude,
  case when not sens.v or s.observer_id = auth.uid() then s.longitude else c.longitude end as longitude,
  s.observed_on,
  s.scientific_name,
  s.class_name,
  s.gbif_species_key,
  s.created_at,
  p.display_name as observer_display_name,
  (select count(*) from public.identifications i
    where i.submission_id = s.id and i.verdict = 'agree') as confirmation_count,
  (sens.v and s.observer_id is distinct from auth.uid()) as location_obscured
from public.submissions s
cross join lateral (select public.submission_is_sensitive(s.id, s.scientific_name) as v) sens
left join public.profiles p on p.id = s.observer_id
left join public.obscuring_cells c on c.cell = public.h3_parent_res5(s.hex_id)
where s.status = 'approved';

revoke all on public.approved_submissions from anon, authenticated, public;
grant select on public.approved_submissions to anon, authenticated;
